[project]
name = "data"
version = "1.0.0"
description = "Data project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = [
    "ahorramas",
    "carrefour",
]
