[project]
name = "ahorramas"
version = "0.1.0"
description = "Ahorramas data project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "polars>=1.32.3",
    "python-dotenv>=1.1.1",
    "redis>=6.4.0",
    "requests>=2.32.5",
]
